title: Urbania
description: Construcción y remodelación premium en Medellín
url: "https://constructoraurbania.com"
baseurl: ""

permalink: pretty

collections:
  proyectos:
    output: true
    permalink: /proyectos/:name/

defaults:
  - scope:
      path: ""
      type: "proyectos"
    values:
      layout: "proyecto"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

plugins:
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - _blog
  - _config
  - n8n
