backend:
  name: github
  repo: juangui104/urbania-web
  branch: main
  base_url: https://roaring-sable-485c30.netlify.app
media_folder: "assets/images/uploads"
public_folder: "/assets/images/uploads"
locale: 'es'
collections: []
