backend:
  name: github
  repo: juangui104/urbania-web
  branch: main
  base_url: https://constructoraurbania.com
  auth_endpoint: api/auth

media_folder: "assets/images/uploads"
public_folder: "/assets/images/uploads"

locale: 'es'

collections: []
